CREATE TABLE `sofia`.`user` (
  `id` BIGINT(10),
  `name` VARCHAR(30) NOT NULL,
  `phone_no` BIGINT(10) NOT NULL,
  `account_id` BIGINT(10) NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`account_id`) REFERENCES sofia.account(id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `sofia`.`device` (
  `id` BIGINT(10),
  `phone_no` BIGINT(10),
  `is_primary` BOOLEAN,
  `status` BOOLEAN,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (phone_no) REFERENCES sofia.user(phone_no),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sofia`.`transaction` (
  id BIGINT(10),
  role_name VARCHAR(30) NOT NULL,

  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sofia`.`account` (
  id BIGINT(10),
   realized_balance DECIMAL DEFAULT 0.0;
   unrealized_balance DECIMAL DEFAULT 0.0;

  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;